
services:
  ##this image comes with a vnc server and you can access the ui using the ports in the browser
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - "TITLE=Kali Linux" #optional
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    stdin_open: true
    tty: true
    networks:
      - localnet
    # restart: unless-stopped
  ##this is a custom build image with no gui but comes with all the tools preinstalled and its faster
  kali:
    image: ghcr.io/harshav167/tupperwares/kali:latest
    container_name: kali_vm
    stdin_open: true
    tty: true
    networks:
      - localnet

  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu_vm
    stdin_open: true
    tty: true
    networks:
      - localnet

  metasploitable:
    image: tleemcjr/metasploitable2:latest
    container_name: metasploitable_vm
    stdin_open: true
    tty: true
    command: sh -c "/bin/services.sh && bash"
    networks:
      - localnet

  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    stdin_open: true
    tty: true
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
