
services:
  kali:
    image: ghcr.io/harshav167/tupperwares/kali:latest
    container_name: kali_vm
    stdin_open: true
    tty: true
    networks:
      - localnet

  ubuntu:
    image: ubuntu:22.04
    container_name: ubuntu_vm
    stdin_open: true
    tty: true
    networks:
      - localnet

  metasploitable:
    image: tleemcjr/metasploitable2:latest
    container_name: metasploitable_vm
    stdin_open: true
    tty: true
    command: sh -c "/bin/services.sh && bash"
    networks:
      - localnet

  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    stdin_open: true
    tty: true
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
